// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfhk2POY3kIfHx3Es_vztzg6mvT_bVNW0',
    appId: '1:162734794259:web:fe1a71d62c2430d04b01e6',
    messagingSenderId: '162734794259',
    projectId: 'skillbridge-e6eb9',
    authDomain: 'skillbridge-e6eb9.firebaseapp.com',
    storageBucket: 'skillbridge-e6eb9.firebasestorage.app',
    measurementId: 'G-S38LL17QLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4jQfobv6HZbqcwFl92ecz6O8PEG8jicg',
    appId: '1:162734794259:android:0f61f8b530a2d4734b01e6',
    messagingSenderId: '162734794259',
    projectId: 'skillbridge-e6eb9',
    storageBucket: 'skillbridge-e6eb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnotdn8_BTslQTGWbY0eaQSg1GnOk8_vU',
    appId: '1:162734794259:ios:ec082384e157d2704b01e6',
    messagingSenderId: '162734794259',
    projectId: 'skillbridge-e6eb9',
    storageBucket: 'skillbridge-e6eb9.firebasestorage.app',
    iosBundleId: 'com.example.skillbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnotdn8_BTslQTGWbY0eaQSg1GnOk8_vU',
    appId: '1:162734794259:ios:ec082384e157d2704b01e6',
    messagingSenderId: '162734794259',
    projectId: 'skillbridge-e6eb9',
    storageBucket: 'skillbridge-e6eb9.firebasestorage.app',
    iosBundleId: 'com.example.skillbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfhk2POY3kIfHx3Es_vztzg6mvT_bVNW0',
    appId: '1:162734794259:web:ab5a511b87d1f0834b01e6',
    messagingSenderId: '162734794259',
    projectId: 'skillbridge-e6eb9',
    authDomain: 'skillbridge-e6eb9.firebaseapp.com',
    storageBucket: 'skillbridge-e6eb9.firebasestorage.app',
    measurementId: 'G-71SCZ4R6JK',
  );
}
